### ISSUE TITLE
adding the PKCS11 library to ssh-agent on Mac

### ISSUE THREAD

**Issue by jonknapp** [jamesog/yubikey-ssh#1]
The command `ssh-add -s /usr/local/lib/opensc-pkcs11.so` failed for me after asking for a passphrase and failing every time.

I instead got things to work by adding a `~/.ssh/config` file with the following line:

```
PKCS11Provider /usr/local/lib/opensc-pkcs11.so
```

Everything else worked like a charm!

**Comment by jamesog** [comment]
That's interesting. How did you initialise the PIV key? Does it have touch or PIN enabled?

I didn't spot this issue when you created it (sorry about that) but if you still have a record of all the commands you ran that might help.

Glad the ssh config entry works though!

**Comment by jonknapp** [comment]
The key I'm using does not have touch enabled. Not sure if that would cause some differences or not.

Over a bit of time, I found that the `tokend` process of OpenSC would block access to another key I had with GPG signing. After force killing the `tokend` process (`ps aux | grep [Y]ubi`) I could use GPG signing again. This may have been related to the issue I was running into.

In the end, I removed the `cask` install of `opensc` and used the normal `brew install opensc` to fit my needs. That stopped the rouge `tokend` process from hijacking card access and I can use one Yubikey for as-needed SSH and another for GPG signing that I always keep inserted.

My `~/.ssh/config` file ended up looking like this (which I think is the same result?):

```
Host *
  PKCS11Provider /usr/local/lib/opensc-pkcs11.so
```

To be honest, not sure if installing through cask, uninstalling, then moving to the lib version with homebrew got me past a different issue or not. This ended up working for me though. YMMV

I mostly wanted to add info in case others drop here from a search result. I'll close out the issue now and thanks again for the writeup!

**Comment by jamesog** [comment]
Great, thanks for that!

When I originally started this I was using the normal `brew` package, but discovered issues with the location of the .so because `ssh-agent` has a list of paths fixed at compile-time for which it'll load PKCS11 libraries, so I had to symlink from the Homebrew-installed location to `/usr/local/lib`. The cask version just installs it there anyway.

Your config should have the same result. You might only want the `ssh-agent` version if you've got a PIN enabled and want the agent to cache the PIN. Personally I just have touch enabled so I don't need it loaded in the agent and use it exactly the same way you do.
